### ISSUE TITLE
[BUG] Automatic Item Piles edit content dialouge

### ISSUE THREAD

**Issue by ChobitsCrazy** [ironmonk88/monks-tokenbar#306]
**Describe the bug**
During dialogue to convert tokens automatically to item piles adjusting their items and currency does not reflect after the token is converted to an item pile.

**To Reproduce**
1.Put humanoid enemy in combat and start combat.
2.Kill the humanoid enemy and end combat.
3.During the dialogue popup adjust the items and currency for the humanoid enemy
![image](https://user-images.githubusercontent.com/21301107/202314312-81b267a0-0296-483b-b594-5f28acd49051.png)

4.Open the new item pile for the humanoid enemy to discover no changes have been made.
![image](https://user-images.githubusercontent.com/21301107/202314372-123688c8-a50c-410d-9fad-11acfc917e56.png)

**Expected behavior**
Item pile should reflect the new changed items/currencies.

**Screenshots**
Provided in the steps

**Please complete as much of the following information as possible:**
 - Browser: Installed Ver.
 - Foundry Version: 10.290
 - System: DND5e
 - Module version: 10.3
 - Are there any errors in the console: No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Tested interaction with no other modules installed

**Comment by ironmonk88** [comment]
I believe this was already fixed.  If it hasn't been, please re-open the ticket.

**Comment by ChobitsCrazy** [comment]
Issue still persists, tested with another token in the latest update
Foundry: 11.315
DnD5e: 2.4.1
Tokenbar: 11.09
![image](https://github.com/ironmonk88/monks-tokenbar/assets/21301107/af059ac0-b262-4825-80ad-81044c23e519)
![image](https://github.com/ironmonk88/monks-tokenbar/assets/21301107/86c06f38-5862-477f-8dd9-5650dec35a38)

**Comment by ChobitsCrazy** [comment]
Hope this helps recreate the issue:
https://github.com/ironmonk88/monks-tokenbar/assets/21301107/c85e0b80-c1f1-4cc9-9adb-56ef7c61a1a2

**Comment by ChobitsCrazy** [comment]
Current settings
![image](https://github.com/ironmonk88/monks-tokenbar/assets/21301107/18d3bcd8-74d4-4397-b33c-ffd79f663fd4)

**Comment by ChobitsCrazy** [comment]
Currently working correctly in the current version.
