### ISSUE TITLE
[BUG] Draggable Off-Screen

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-tokenbar#529]
Tokenbar can be dragged off the screen on the top and right sides of the screen.

Foundry 12.331
Tokenbar 12.02

**Comment by ironmonk88** [comment]
Fixed in the latest version

**Comment by Crowguard** [comment]
Still an issue with TB 12.03.

https://github.com/user-attachments/assets/ecc136ff-d0a4-4fc5-a1ba-94722fbcced4
